# Site settings
author: Teinelle Charles
title: CODING IN HEELS
header-img: img/home-bg.png
email: teinelledcharles@gmail.com
copyright_name: Teinelle Charles
description: > # this means to ignore newlines until "baseurl:"
  Just a babe coding 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  danaeeblacc

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
